# ----------- CONFIGURABLE START -----------
title:            "HB with HS"
description:      "Such theme, very cool."
remote_theme:     muan/scribble
url:              https://HBwithHS.github.io # Site url, without a slash at the end.
signoff:          "Hyesung" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons
future:           true

plugins:
        - jekyll-maps
maps:
        google:
                api_key: AIzaSyBPf-1UBKZKGljh25oCFVDHb7_xpQwPGQo


links:
  - name:         Home
    url:          /
    external:     false
  - name:         Menu
    url:          /menu
    external:     false
  - name:         Contents
    url:          /contents
    external:     false
  - name:         Dates
    url:          /dates
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
